language: node_js
node_js:
  - "node"
warnings_are_errors: false
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
deploy:
  - provider: firebase
    skip_cleanup: true
    on:
      branch: master
    token:
      secure: "wAO1tqDrgqVAdDP9+/hreqsg9rWlux9S08Y/kyxDEMfxwI9EFD8lWI4Gt8+toIvr4POf4RQOL6kiH2Huh3jv8h1QB94Vzoa6ZTWsruoi625ykYFiM3ej9+qCSXOxiRSTN77cKTOMPa7QrG8VppVeAe2bFRXLAAQrBTmRlvD1b6FmSb6vj4751nu/HUAwI/S1Nb/tDSlkUShAfpmdmackaE7q8EAO7Wj8/ZbzGFzbNFlzIb6jkuVNREjFjrMQdBsffevEkC1ZMHxhGX7MEs3PVZsgLIMh/aXX6IdANktWYmRKxMJKadEGs0TUa4e+c4lLWIthB3pGZkrhijxVC0y5/boroGqi/479K3F9hCmAkFNxoW9d2MJhIqEO1hp6NtU70/F1KR+MpzutTLyRKDaop5Cor1+N3hhE9LiKhvRkJ8YgXuMWyiT6Cq+DTqAlscZrpg2XjLuir+xJckKfWMPz4YzjBNGPn21oZ20GAZfZbn7oK87F+/Nqx+EBqBvnNn3b1TH/LqtbCVl/p3D1yCctSAoKambBnPRnUC+XygrRDSP9CTiCg7XxjRF00lnabN9GATyBW8JK0LToD3UZMngyF/9VqQYvjnHN62Nbl7R6OZZKx7HNdgOscA9NGo5rUCHAA4ry05w6KP5zjcGUebF1W9cRbIKl9M0anWgQvcV0NJ0="

